# Generated by Django 2.1.1 on 2019-06-16 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
